name: floard
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  common_utils: ^1.1.3
  flutter_screenutil: ^1.1.0
  azlistview: ^0.1.2
  cached_network_image: ^2.2.0+1
  share_extend: ^1.1.5
  flutter_easyloading: ^1.1.4
  flutter_show_more: ^0.1.2
  gzx_dropdown_menu: ^1.0.3
  pull_to_refresh: ^1.5.8
  modal_bottom_sheet: ^0.1.5
  flutter_staggered_grid_view: ^0.3.0 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
    - assets/data/countrycode.json
    
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
